# 应用服务 WEB 访问端口
server.port=8080

# 数据库连接配置 (请修改为实际的数据库连接信息)
# Old single datasource config
# spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCL
# spring.datasource.username=DMISLN_WIND
# spring.datasource.password=DMISLN_WIND
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Multiple Datasource Config
custom.datasource.list[0].id=LocalOracle
custom.datasource.list[0].name=LocalOracle
custom.datasource.list[0].url=jdbc:oracle:thin:@//localhost:1521/ORCL
custom.datasource.list[0].username=DMISLN_WIND
custom.datasource.list[0].password=DMISLN_WIND
custom.datasource.list[0].driver-class-name=oracle.jdbc.OracleDriver
custom.datasource.list[1].id=FaceAllOracle
custom.datasource.list[1].name=FaceAllOracle
custom.datasource.list[1].url=jdbc:oracle:thin:@//192.168.0.125:1521/ORCL
custom.datasource.list[1].username=system
custom.datasource.list[1].password=Oracle@123
custom.datasource.list[1].driver-class-name=oracle.jdbc.OracleDriver


